apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-local-pv
  namespace: logging
spec:
  capacity:
    storage: 45Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es-data-db
  local:
    path: /data/local/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - garfield-optiplex-7050
