apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: logging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: es-data-db
